# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PurpleOrangeGames
email: tiago.carvalho@purpleorangegames.com
description: > # this means to ignore newlines until "baseurl:"
  PurpleOrangeGames is an indie group of developers and artists that
  work on their spare time making what they love, games.
  We have several projects being made. Usually each project is
  maintained by one member of the group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.purpleorangegames.com" # the base hostname & protocol for your site
twitter_username: purpleor
github_username:  purpleorangegames

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker